        <!-- JS -->
        {!! Html::script('js/jquery-1.11.1.min.js') !!}
        {!! Html::script('js/jquery-migrate-1.2.1.min.js') !!}
        {!! Html::script('js/jquery.easing.1.3.js') !!}
        {!! Html::script('js/bootstrap.min.js') !!}
        {!! Html::script('js/SmoothScroll.js') !!}
        {!! Html::script('js/jquery.scrollTo.min.js') !!}
        {!! Html::script('js/jquery.localScroll.min.js') !!}
        {!! Html::script('js/jquery.ba-hashchange.min.js') !!}
        {!! Html::script('js/jquery.viewport.mini.js') !!}
        {!! Html::script('js/jquery.countTo.js') !!}
        {!! Html::script('js/jquery.appear.js') !!}
        {!! Html::script('js/jquery.sticky.js') !!}
        {!! Html::script('js/jquery.parallax-1.1.3.js') !!}
        {!! Html::script('js/jquery.fitvids.js') !!}
        {!! Html::script('js/owl.carousel.min.js') !!}
        {!! Html::script('js/isotope.pkgd.min.js') !!}
        {!! Html::script('js/imagesloaded.pkgd.min.js') !!}
        {!! Html::script('js/jquery.magnific-popup.min.js') !!}
        <!--{!! Html::script('http://maps.google.com/maps/api/js?sensor=false&amp;language=en') !!}-->
        {!! Html::script('js/gmap3.min.js') !!}
        {!! Html::script('js/all.js') !!}
        {!! Html::script('js/contact-form.js') !!}
        {!! Html::script('js/animations.min.js') !!}
        {!! Html::script('js/placeholder.js') !!}
